const MAIN_PATH = process.env.MAIN_PATH
const USER_FTP = process.env.USER_FTP
const PASSWORD_FTP = process.env.PASSWORD_FTP
const URL_URBAGIS_FTP = process.env.URL_URBAGIS_FTP
const URBAGIS_FTP_PATH_FILES = process.env.URBAGIS_FTP_PATH_FILES
const URBAGIS_CARDIQUE_URL = process.env.URBAGIS_CARDIQUE_URL
const URBAGIS_ACCESS_TOKEN = process.env.URBAGIS_ACCESS_TOKEN
const WEATHER_STATIONS = process.env.WEATHER_STATIONS
const EARCA_MOVIL_ID = process.env.EARCA_MOVIL_ID
const EARCA_MOVIL_TASK = process.env.EARCA_MOVIL_TASK
const CLEAR_FILES_TASK = process.env.CLEAR_FILES_TASK

module.exports = {
	MAIN_PATH,
	USER_FTP,
	PASSWORD_FTP,
	URL_URBAGIS_FTP,
	URBAGIS_FTP_PATH_FILES,
	URBAGIS_CARDIQUE_URL,
	URBAGIS_ACCESS_TOKEN,
	WEATHER_STATIONS,
	EARCA_MOVIL_ID,
	EARCA_MOVIL_TASK,
	CLEAR_FILES_TASK
}